version: '3.7'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  user_uploads: # Bind to a local directory on the host system
    # Ref: https://github.com/docker/compose/issues/2957#issuecomment-403175803
    driver: local
    driver_opts:
      type: none
      o: bind
      device:
        /var/lz-uploads/

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: locuszoom_plotting_service_production_django
    depends_on:
      - postgres
      - redis
    volumes:
      - user_uploads:/lz-uploads:z
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - "5000:5000"
    restart:
      unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: locuszoom_plotting_service_production_postgres
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "max_connections=500"
      - "-c"
      - "shared_buffers=1GB"
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    restart:
      unless-stopped

  redis:
    image: redis:3.2
    restart:
      unless-stopped

  celeryworker:
    <<: *django
    image: locuszoom_plotting_service_production_celeryworker
    command: /start-celeryworker
    ports: []
    restart:
      unless-stopped

  celerybeat:
    <<: *django
    image: locuszoom_plotting_service_production_celerybeat
    command: /start-celerybeat
    ports: []
    restart:
      unless-stopped

  flower:
    <<: *django
    image: locuszoom_plotting_service_production_flower
    ports:
      - "5555:5555"
    command: /start-flower
    restart:
      unless-stopped
